
services:
  postgresdb:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  task-tracker-backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      postgresdb:
        condition: service_started

volumes:
  postgres-data: