spring:
  application:
    name: fitness-app
  main:
    banner-mode: 'off'
    log-startup-info: false
  jpa:
    properties:
      hibernate:
        format-sql: 'true'
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness
    username: postgres
    password: 123

hibernate:
  format_sql: 'true'
  show_sql: 'true'

server:
  servlet:
    context-path: /api/v1
  port: '8080'
