spring:
  application:
    name: fitness-app
  main:
    banner-mode: 'off'
    log-startup-info: false
  jpa:
    properties:
      hibernate:
        format-sql: 'true'
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/fitnessapp
#  liquibase:
#    default-schema: public
#    enabled: true
#    change-log: classpath:/db/changelog/db.changelog-master.json

hibernate:
  format_sql: 'true'
  show_sql: 'true'

server:
  servlet:
    context-path: /api/v1
  port: '8080'
